= Changelog

== Version 0.5.0

Date: unreleased

- Breaking change: now encode and decode functions returns instances of success or failure of exception
  monad instead of instances of either monad.
- Breaking change: now sign/unsign methods raises exceptions instead of simply return nil. This allows
  libraries and applications that does not works with monads workis like a usual, using jvm
  exceptions and know the specific error instead of useless nil.
- Add basic support for JWE.
  Implemented key algorithms: DIR.
  Implemented content encryption algorithms: A128CBC-HS256, A192CBC-HS384, A256CBC-HS512.


== Version 0.4.2

Date: 2015-03-29

- Bug fix related to :iat param validating on jws. (thanks to @tvanhens)


== Version 0.4.1

Date: 2015-03-14

- Update nippy version from 2.7.1 to 2.8.0
- Update buddy-core from 0.4.0 to 0.4.2
- Update cats from 0.3.2 to 0.3.4


== Version 0.4.0

Date: 2015-02-22

- Add encode/decode functions to JWS/JWT implementation. Them instead of return
  plain value, return a monadic either. That allows granular error reporting
  instead something like nil that not very useful. The previous sign/unsign
  are conserved for backward compatibility but maybe in future will be removed.
- Rename parameter `maxage` to `max-age` on jws implementation. This change
  introduces a little backward incompatibility.
- Add "compact" signing implementation as replacemen of django based one.
- Django based generic signing is removed.
- Update buddy-core version to 0.4.0


== Version 0.3.0

Date: 2014-01-18

- First version splitted from monolitic buddy package.
- No changes from original version.
