= buddy-sign - High level message signing.
Andrey Antukh, <niwi@niwi.be>
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

Buddy *sign* module is dedicated to provide a high level abstraction
for web ready message signing.

It can be used for several purposes:

- Safely send/store signed messages.
- Safely store session data in cookies instead of a database (this prevents others
  from changing session content)
- Self contained token generation for use with completely stateless token based authentication.


== Project Maturity

Since _buddy-sign_ is a young project there can be some API breakage.


== Install

This section covers the _buddy-sign_ library installing process and its requirements.

=== Requirements

_buddy-sign_ is tested with these platforms:

- JDK7
- JDK8


=== Leiningen

The simplest way to use _buddy-sign_ in a clojure project, is by including it in the dependency
vector on your *_project.clj_* file:

._on project.clj_
[source,clojure]
----
[buddy/buddy-sign "0.4.2"]
----

=== Gradle

If you are using gradle, this is a dependency line for gradle dsl:

[source,groovy]
----
compile "buddy:buddy-sign:0.4.2"
----


=== Get the Code

_buddy-sign_ is open source and can be found on link:https://github.com/funcool/buddy-sign[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/buddy-sign
----



[[jws]]
== Json Web Signature/Token

[small]#New in version: 0.2#

JSON Web Signature (JWS) represents content secured with digital
signatures or Message Authentication Codes (MACs) using JavaScript
Object Notation (JSON) as serialization format.

.Supported Algorithms
[options="header"]
|=====================================================================================
|Algorithm name     | Hash algorithms   | Keywords           | Priv/Pub Key?
|Elliptic Curve DSA | sha256, sha512    | `:es256`, `:es512` | Yes
|RSASSA PSS         | sha256, sha512    | `:ps256`, `:ps512` | Yes
|RSASSA PKCS1 v1_5  | sha256, sha512    | `:rs256`, `:rs256` | Yes
|HMAC               | sha256*, sha512   | `:hs256`, `:hs256` | No
|=====================================================================================

.List of rfcs related JWS/JWT/JWA:
- http://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32
- http://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40
- http://tools.ietf.org/html/draft-ietf-jose-json-web-signature-40


=== Signing and unsignin data

Due to the nature of the storage format, the input is restricted mainly to json objects
in the current version.

.Example sign data using JWS
[source, clojure]
----
(require '[buddy.sign.jws :as jws])

;; Sign data using default `:hs256` algorithm that does not
;; requres special priv/pub key.
(def data (jws/encode {:userid 1} "secret"))

;; data will contains omething to
;; #<Right [eyJ0eXAiOiJKV1MiLCJhbGciOiJIU...]>

(jws/decode @data "secret")
;; => {:userid 1}
----

The *encode* and *decode* methods returns a monadic either defined in
link:https://github/funcool/cats[cats library]. This allows more granural
error reporting when something wrong is happens in the validation process.

That functions are introduced in *buddy-sign 0.4.0*. Also, the previos
*sign* and *unsign* functions are conserved for backward compatibility
and are still returning plain values.


=== Using Digital Signature algorithms

In order to use any of digital signature algorithms you must have a private/public key.
If you don't have one, don't worry, it is very easy to generate it using *openssl*, see
this <<generate-keypairs,faq entry>>.

Now, having generated a key pair, you can sign your messages using one
of supported digital signature algorithms.

.Example of signing a string using _es256_ (eliptic curve dsa) algorithm.
[source, clojure]
----
(require '[buddy.sign.jws :as jws])
(require '[buddy.core.keys :as keys])

;; Create keys instances
(def ec-privkey (keys/private-key "ecprivkey.pem"))
(def ec-pubkey (keys/public-key "ecpubkey.pem"))

;; Use them like plain secret password with hmac algorithms for sign
(def signed-data (jws/encode {:foo "bar"} ec-privkey {:alg :es256}))

;; And unsign
(def unsigned-data (jws/decode @signed-data ec-pubkey {:alg :es256}))
----

== Compact message signing

Compact high level message signing implementation.

It has high influence by django's cryptographic library and json web signature/encryption
but with focus on have a compact representation. It's build on top of fantastic ptaoussanis/nippy
serialization library.

This singing implementation is not very efficient with small messages, but is very space efficient
with big messages.

The purpose of this implementation is for secure message transfer, it is not really good candidate
for auth token because of not good space efficiency for small messages.

.Supported Algorithms
[options="header"]
|=====================================================================================
| Algorithm name     | Hash algorithms   | Keywords           | Priv/Pub Key?
| Elliptic Curve DSA | sha256, sha512    | `:es256`, `:es512` | Yes
| RSASSA PSS         | sha256, sha512    | `:ps256`, `:ps512` | Yes
| RSASSA PKCS1 v1_5  | sha256, sha512    | `:rs256`, `:rs256` | Yes
| Poly1305           | aes, twofish, serpent | `:poly1305-aes`, `:poly1305-serpent`, `:poly1305-twofish` | No
| HMAC               | sha256*, sha512   | `:hs256`, `:hs256` | No
|=====================================================================================

+++*+++ indicates the default value.

[NOTE]
====
Only HMAC and Poly1305 based algorithms support plain text secret keys, If you want to use
Digital Signature instead of hmac then you must have a key pair (public and private).
====

=== Signing and unsigning data

With difference with jwt/jws, this implementation is not limited to hash-map like objects,
and you can sign any clojure valid type.

Let see an example:

.Example signing arbitrary data using compact signing.
[source,clojure]
----
(require '[buddy.sign.compact :as cm])

;; Sign data using default `:hs256` algorithm that does not
;; requres special priv/pub key.
(def data (cm/encode {:userid 1} "secret"))

;; data will contains omething to
;; #<Right [auJ0eXAiOiJKV1MiLCJhbGciOiJIU...]>

(cm/decode @data "secret")
;; => {:userid 1}
----

The *encode* and *decode* methods returns a monadic either defined in
link:https://github/funcool/cats[cats library]. This allows more granural
error reporting when something wrong is happens in the validation process.

Also, the *sign* and *unsign* functions are available, and they are analogous
to *encode*/*decode* but are still returning plain values instead a containers.


Then, you also will be able validate the signed message based in its age:

[source,clojure]
----
(cm/decode @data "secret" {:max-age (* 15 60)})
;; => #<Left [Expired data]>
----


== FAQ

[[generate-keypairs]]
=== How I can generate keypairs?

.Example on how to generate one Elliptic Curve DSA keypair.
[source, bash]
----
# Generating params file
openssl ecparam -name prime256v1 -out ecparams.pem

# Generate a private key from params file
openssl ecparam -in ecparams.pem -genkey -noout -out ecprivkey.pem

# Generate a public key from private key
openssl ec -in ecprivkey.pem -pubout -out ecpubkey.pem
----

.Example on how to generate one RSA keypair.
[source, bash]
----
# Generate aes256 encrypted private key
openssl genrsa -aes256 -out privkey.pem 2048

# Generate public key from previously created private key.
openssl rsa -pubout -in privkey.pem -out pubkey.pem
----

== How to Contribute?

=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _buddy-sign_ should keep these important rules in mind.


=== Procedure

**buddy-sign** unlike Clojure and other Clojure contrib libs, does not have many
restrictions for contributions. Just follow the following steps depending on the
situation:

**Bugfix**:

- Fork the GitHub repo.
- Fix a bug/typo on a new branch.
- Make a pull-request to master.

**New feature**:

- Open new issue with the new feature proposal.
- If it is accepted, follow the same steps as "bugfix".


=== License

_buddy-sign_ is licensed under BSD (2-Clause) license:

----
Copyright (c) 2013-2015, Andrey Antukh <niwi@niwi.be>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
